[package]
name = "amnezia"
description = "Faithful Bevy/Rust remake of MoonDragon Entertainment's Amnezia."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
amnezia-data = { workspace = true }
bevy = { workspace = true }
encoding_rs = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { workspace = true }
winit = { workspace = true }
