use super::{Case, Kind};
use bevy::prelude::*;

const BASE: Case = Case {
    label: "",
    kind: Kind::Fade,
    flashes: false,
    previous: false,
    previous_none: false,
    changed: false,
    erase: true,
    from_erased: false,
    frame: -1,
    center: IVec2::ZERO,
};

pub(super) const CASES: [Case; 26] = [
    Case {
        label: "transition-fade-out",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Fade,
        erase: true,
        from_erased: false,
        frame: 16,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-fade-in",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Fade,
        erase: false,
        from_erased: true,
        frame: 16,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-crossfade",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Fade,
        erase: false,
        from_erased: false,
        frame: 16,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-mosaic-out",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Mosaic,
        erase: true,
        from_erased: false,
        frame: 20,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-mosaic-in",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Mosaic,
        erase: false,
        from_erased: true,
        frame: 12,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-zoom-out",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Zoom,
        erase: true,
        from_erased: false,
        frame: 20,
        center: IVec2::new(16, 200),
    },
    Case {
        label: "transition-zoom-in",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Zoom,
        erase: false,
        from_erased: true,
        frame: 0,
        center: IVec2::new(300, 16),
    },
    Case {
        label: "transition-cut-out",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Cut,
        erase: true,
        from_erased: false,
        frame: 0,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-cut-in",
        flashes: false,
        changed: false,
        previous: false,
        previous_none: false,
        kind: Kind::Cut,
        erase: false,
        from_erased: true,
        frame: 0,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-battle-flash-peak",
        kind: Kind::Zoom,
        flashes: true,
        changed: false,
        previous: false,
        previous_none: false,
        erase: true,
        from_erased: false,
        frame: 0,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-battle-flash-decay",
        kind: Kind::Zoom,
        flashes: true,
        changed: false,
        previous: false,
        previous_none: false,
        erase: true,
        from_erased: false,
        frame: 15,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-battle-zoom",
        kind: Kind::Zoom,
        flashes: true,
        changed: false,
        previous: false,
        previous_none: false,
        erase: true,
        from_erased: false,
        frame: 40,
        center: IVec2::new(16, 200),
    },
    Case {
        label: "transition-previous-scene",
        kind: Kind::Fade,
        flashes: false,
        changed: false,
        previous: true,
        previous_none: false,
        erase: true,
        from_erased: false,
        frame: 16,
        center: IVec2::ZERO,
    },
    Case {
        label: "transition-init-erase",
        changed: true,
        ..BASE
    },
    Case {
        label: "transition-init-show",
        erase: false,
        ..BASE
    },
    Case {
        label: "transition-init-erased-show",
        erase: false,
        from_erased: true,
        ..BASE
    },
    Case {
        label: "transition-init-cut-out",
        kind: Kind::Cut,
        changed: true,
        ..BASE
    },
    Case {
        label: "transition-init-cut-in",
        kind: Kind::Cut,
        erase: false,
        ..BASE
    },
    Case {
        label: "transition-init-battle-flash",
        flashes: true,
        ..BASE
    },
    Case {
        label: "transition-none-visible-erase",
        kind: Kind::None,
        changed: true,
        frame: 5,
        ..BASE
    },
    Case {
        label: "transition-none-visible-show",
        kind: Kind::None,
        erase: false,
        frame: 5,
        ..BASE
    },
    Case {
        label: "transition-none-erased",
        kind: Kind::None,
        erase: false,
        from_erased: true,
        frame: 5,
        ..BASE
    },
    Case {
        label: "transition-erase-current-scene",
        kind: Kind::Cut,
        changed: true,
        frame: 0,
        ..BASE
    },
    Case {
        label: "transition-init-after-none",
        previous_none: true,
        erase: false,
        ..BASE
    },
    Case {
        label: "transition-show-after-none",
        previous_none: true,
        erase: false,
        frame: 16,
        ..BASE
    },
    Case {
        label: "transition-erase-after-none",
        previous_none: true,
        changed: true,
        kind: Kind::Cut,
        frame: 0,
        ..BASE
    },
];
